FROM maxulysse/caw-base:0.9.9

MAINTAINER Maxime Garcia <maxime.garcia@scilifelab.se>

#Install GATK 3.6
RUN wget -q -O /opt/gatk.3.6.zip https://github.com/broadgsa/gatk-protected/archive/3.6.zip
RUN unzip /opt/gatk.3.6.zip -d /opt/
